spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

server:
  servlet:
    session:
      timeout: 60

#logging:
#  level:
#    root: DEBUG
